version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: "daily"
      time: "09:30"
